pipeline{
    agent any
    tools{
        jdk 'jdk21'
        terraform 'terraform'
    }
    stages{
        stage('clean Workspace'){
            steps{
                cleanWs()
            }
        }
        stage('checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/Shraddhabgit/Tetris-v1.git'
            }
        }
        stage('Terraform version'){
             steps{
                 sh 'terraform --version'
                }
        }
        stage('Sonarqube Analysis'){
            steps{
                withSonarQubeEnv('sonarqube') {
                    sh ''' $SCANNER_HOME/usr/local/bin/sonar-scanner   -Dsonar.projectKey=Terraform   -Dsonar.sources=.   -Dsonar.host.url=$SONAR_HOST_URL   -Dsonar.token=$SONAR_AUTH_TOKEN '''
                    
                }
            }
        }
      
        stage('TRIVY FS SCAN') {
            steps {
                sh "trivy fs . > trivyfs.txt"
            }
        }
       
        stage('Terraform init'){
            steps{
                sh 'terraform init'
            }
        }
        stage('Terraform plan'){
            steps{
                sh '''
                cd Jenkins-CICD
                terraform plan
                '''
            }
        }
        stage('Terraform apply'){
            steps{
                sh 'terraform ${action} --auto approve'
            }
        }
    }
}
